/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const StockItem = IDL.Record({
  'id' : IDL.Nat,
  'lowStockThreshold' : IDL.Nat,
  'name' : IDL.Text,
  'isLowStock' : IDL.Bool,
  'quantity' : IDL.Nat,
  'category' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
  'unitPrice' : IDL.Nat,
  'isTrending' : IDL.Bool,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const IncomeSummary = IDL.Record({
  'todaysIncome' : IDL.Nat,
  'totalIncome' : IDL.Nat,
  'monthlyIncome' : IDL.Nat,
});
export const RevenueOverview = IDL.Record({
  'productBreakdown' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
  'totalRevenue' : IDL.Nat,
  'monthlyRevenue' : IDL.Nat,
});
export const Sale = IDL.Record({
  'id' : IDL.Nat,
  'stockItemId' : IDL.Nat,
  'timestamp' : IDL.Int,
  'quantity' : IDL.Nat,
  'totalPrice' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addSale' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], []),
  'addStockItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Opt(ExternalBlob)],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteStockItem' : IDL.Func([IDL.Nat], [], []),
  'getAllStockItems' : IDL.Func([], [IDL.Vec(StockItem)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getIncomeSummary' : IDL.Func([], [IncomeSummary], ['query']),
  'getLowStockItems' : IDL.Func([], [IDL.Vec(StockItem)], ['query']),
  'getRevenueOverview' : IDL.Func([], [RevenueOverview], ['query']),
  'getTodaysSales' : IDL.Func([], [IDL.Vec(Sale)], ['query']),
  'getTrendingStockItems' : IDL.Func([], [IDL.Vec(StockItem)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markTrendingStockItem' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateStockItem' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Opt(ExternalBlob),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const StockItem = IDL.Record({
    'id' : IDL.Nat,
    'lowStockThreshold' : IDL.Nat,
    'name' : IDL.Text,
    'isLowStock' : IDL.Bool,
    'quantity' : IDL.Nat,
    'category' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
    'unitPrice' : IDL.Nat,
    'isTrending' : IDL.Bool,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const IncomeSummary = IDL.Record({
    'todaysIncome' : IDL.Nat,
    'totalIncome' : IDL.Nat,
    'monthlyIncome' : IDL.Nat,
  });
  const RevenueOverview = IDL.Record({
    'productBreakdown' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
    'totalRevenue' : IDL.Nat,
    'monthlyRevenue' : IDL.Nat,
  });
  const Sale = IDL.Record({
    'id' : IDL.Nat,
    'stockItemId' : IDL.Nat,
    'timestamp' : IDL.Int,
    'quantity' : IDL.Nat,
    'totalPrice' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addSale' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], []),
    'addStockItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Opt(ExternalBlob)],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteStockItem' : IDL.Func([IDL.Nat], [], []),
    'getAllStockItems' : IDL.Func([], [IDL.Vec(StockItem)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getIncomeSummary' : IDL.Func([], [IncomeSummary], ['query']),
    'getLowStockItems' : IDL.Func([], [IDL.Vec(StockItem)], ['query']),
    'getRevenueOverview' : IDL.Func([], [RevenueOverview], ['query']),
    'getTodaysSales' : IDL.Func([], [IDL.Vec(Sale)], ['query']),
    'getTrendingStockItems' : IDL.Func([], [IDL.Vec(StockItem)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markTrendingStockItem' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateStockItem' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Opt(ExternalBlob),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };