/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminDashboard {
  'totalProducts' : bigint,
  'outOfStockProducts' : bigint,
  'todaysIncome' : bigint,
  'totalIncome' : bigint,
  'totalEnquiries' : bigint,
  'monthlyIncome' : bigint,
}
export interface Customer {
  'id' : bigint,
  'name' : string,
  'isRepeatCustomer' : boolean,
  'phone' : string,
}
export interface Enquiry {
  'id' : bigint,
  'name' : string,
  'createdAt' : Time,
  'message' : string,
  'phone' : string,
}
export interface Product {
  'id' : bigint,
  'inStock' : boolean,
  'name' : string,
  'imageUrl' : [] | [string],
  'isHidden' : boolean,
  'quantity' : bigint,
  'category' : ProductCategory,
  'price' : bigint,
}
export type ProductCategory = { 'clothing' : null } |
  { 'food' : null } |
  { 'toys' : null } |
  { 'furniture' : null } |
  { 'electronics' : null };
export interface SalesReport {
  'monthlySales' : bigint,
  'productWiseSales' : Array<[bigint, bigint]>,
  'dailySales' : bigint,
  'totalSales' : bigint,
}
export type Time = bigint;
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCustomer' : ActorMethod<[string, string], bigint>,
  'addEnquiry' : ActorMethod<[string, string, string], bigint>,
  'addProduct' : ActorMethod<
    [string, ProductCategory, bigint, bigint, [] | [string]],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'editProduct' : ActorMethod<
    [bigint, string, ProductCategory, bigint, bigint, [] | [string]],
    undefined
  >,
  'getAdminDashboard' : ActorMethod<[], AdminDashboard>,
  'getAllEnquiries' : ActorMethod<[], Array<Enquiry>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomers' : ActorMethod<[], Array<Customer>>,
  'getMonthlySalesReport' : ActorMethod<[], SalesReport>,
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getTodaysEnquiries' : ActorMethod<[], Array<Enquiry>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hideProduct' : ActorMethod<[bigint], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateRepeatCustomerStatus' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];